services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    volumes:
      - ${POSTGRES_VOLUME_DIR:-./postgres-data}:/var/lib/postgresql/data

  web:
    build: ./resources/docker
    command:
      - ./resources/docker/run.sh
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD} # Used by psql and other PostgreSQL command-line tools.
      DATABASE_HOST: db
    ports:
      - "4000:4000"
    volumes:
      - .:/app
