services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: ./resources/docker
    command:
      - ./resources/docker/run.sh
    depends_on:
      - db
    environment:
      PGPASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
    ports:
      - "4000:4000"
    volumes:
      - .:/app

volumes:
  postgres-data:
